### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by ViktorC** [ViktorC/CppNN#2]
- [x] Test automation using Google Test
- [ ] CMake build
- [x] Deconvolutional layer
- [x] Convolution, deconvolution, and pooling for 1st and 2nd rank data
- [x] Broadcast and reshaping layers
- [ ] Pixel shuffle layer
- [ ] FFT and/or Winograd filtering for CPU convolution
- [ ] **More comprehensive GPU support and cuDNN utilization**
- [ ] **Passing data between device layers without copying to and from the host**
- [x] Network serialization and de-serialization
- [x] PPM codec
- [ ] GIF codec
- [ ] WAV codec
- [x] IMDB data set provider
- [ ] AN4 data set provider
- [x] Working GAN example
- [x] NLP example (word2vec, sentiment analysis)
- [ ] **Text generation example**
- [ ] **Temporal convolutional network example**
- [ ] **Speech recognition example**
- [ ] **Speech synthesis example**
- [ ] TF-IDF preprocessor
- [ ] LDA preprocessor
- [x] AMSGrad optimizer
- [ ] GRU network
- [ ] CTC loss function
- [ ] **Object detection support (YOLO)**
- [ ] **Hyper parameter tuning framework (grid search, gaussian optimization, evolutionary algorithms)**
